# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMVMR_POCov <- function(Outcome, SD, XCovariate, WCovariate, Trial, Treat, Npt, c01, c02, K, T, ndiscard, nskip, nkeep, verbose) {
    .Call(`_BayesMeta_BMVMR_POCov`, Outcome, SD, XCovariate, WCovariate, Trial, Treat, Npt, c01, c02, K, T, ndiscard, nskip, nkeep, verbose)
}

BMVSMR <- function(Outcome, Covariate, Treat, Patient, Trial, a0, b0, c1, c2, c3, d0, S0, d1, S1, v0, tau, K, ndiscard, nskip, nkeep, verbose) {
    .Call(`_BayesMeta_BMVSMR`, Outcome, Covariate, Treat, Patient, Trial, a0, b0, c1, c2, c3, d0, S0, d1, S1, v0, tau, K, ndiscard, nskip, nkeep, verbose)
}

BayesNMR <- function(y, sd, x, z, ids, iarm, npt, nu, c01_inv, c02_inv, K, nT, ndiscard, nskip, nkeep, verbose, beta_init, phi_init, sig2_init) {
    .Call(`_BayesMeta_BayesNMR`, y, sd, x, z, ids, iarm, npt, nu, c01_inv, c02_inv, K, nT, ndiscard, nskip, nkeep, verbose, beta_init, phi_init, sig2_init)
}

calc_modelfit_dic <- function(y, x, z, ids, iarm, npt, nu, betas, sig2s, phis, lams, Rhos, K, nT, nkeep, verbose) {
    .Call(`_BayesMeta_calc_modelfit_dic`, y, x, z, ids, iarm, npt, nu, betas, sig2s, phis, lams, Rhos, K, nT, nkeep, verbose)
}

calc_modelfit_lpml <- function(y, x, z, ids, iarm, npt, nu, betas, sig2s, phis, lams, Rhos, K, nT, nkeep, verbose) {
    .Call(`_BayesMeta_calc_modelfit_lpml`, y, x, z, ids, iarm, npt, nu, betas, sig2s, phis, lams, Rhos, K, nT, nkeep, verbose)
}

